layers:
  APTMAK:
  - V
  - W
  - F
  - P
  - B
  - J
  - L
  - U
  - Y
  - ''''
  - {t: R, h: '$$mdi:apple-keyboard-control$$'}
  - {t: S, h: '$$mdi:apple-keyboard-option$$'}
  - {t: T, h: '$$mdi:apple-keyboard-shift$$'}
  - {t: H, h: '$$mdi:apple-keyboard-command$$'}
  - K
  - X
  - {t: N, h: '$$mdi:apple-keyboard-command$$'}
  - {t: A, h: '$$mdi:apple-keyboard-shift$$'}
  - {t: I, h: '$$mdi:apple-keyboard-option$$'}
  - {t: O, h: '$$mdi:apple-keyboard-control$$'}
  - ;
  - C
  - G
  - D
  - Q
  - Z
  - M
  - {t: ',', s: ;}
  - {t: ., s: ':'}
  - /
  - {type: none}
  - {t: '$$mdi:keyboard-return$$', h: NUM}
  - {t: '$$mdi:keyboard-space$$', h: NAV, s: $$dot_spc$$}
  - {t: E, h: SYM}
  - {t: '$$mdi:apple-keyboard-shift$$', h: '$$mdi:star-three-points$$', s: '$$mdi:caps-lock$$'}
  - {type: none}
  NAV:
  - {type: none}
  - {type: none}
  - $$tabler:square-x$$
  - $$tabler:browser-x$$
  - {type: none}
  - {type: none}
  - $$pg_dn$$
  - $$mdi:arrow-up-bold$$
  - $$pg_up$$
  - {type: none}
  - {t: '$$mdi:apple-keyboard-control$$', h: '$$tabler:sticker$$'}
  - {t: '$$mdi:apple-keyboard-option$$', h: '$$tabler:sticker$$'}
  - {t: '$$mdi:apple-keyboard-shift$$', h: '$$tabler:sticker$$'}
  - {t: '$$mdi:apple-keyboard-command$$', h: '$$tabler:sticker$$'}
  - {type: none}
  - {t: '$$mdi:backspace-reverse-outline$$', h: WORD}
  - $$mdi:arrow-left-bold$$
  - $$mdi:arrow-down-bold$$
  - $$mdi:arrow-right-bold$$
  - $$mdi:monitor-screenshot$$
  - {type: none}
  - {t: '$$mdi:swap-horizontal$$', h: Windows}
  - $$mdi:power-sleep$$
  - {t: '$$mdi:swap-horizontal$$', h: Tabs}
  - {type: none}
  - {type: none}
  - $$screen-prev$$
  - {type: none}
  - $$tabler:screen-share$$
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: held}
  - {t: ▽, type: trans}
  - {type: none}
  - {type: none}
  SYM:
  - {type: none}
  - '@'
  - '#'
  - $/€
  - '%'
  - ^
  - +
  - '*'
  - '&'
  - {type: none}
  - '?'
  - '`'
  - \
  - '='
  - '~'
  - _
  - '-'
  - /
  - '|'
  - '!'
  - {type: none}
  - {t: '`', h: '$$tabler:sticker$$'}
  - {t: ´, h: '$$tabler:sticker$$'}
  - {type: none}
  - {type: none}
  - {type: none}
  - <
  - '>'
  - °
  - {type: none}
  - {type: none}
  - {t: ▽, type: trans}
  - {t: ▽, type: trans}
  - {type: held}
  - {type: none}
  - {type: none}
  NUM:
  - F12
  - F7
  - F8
  - F9
  - '*'
  - +
  - '7'
  - '8'
  - '9'
  - {type: none}
  - F10
  - F4
  - F5
  - F6
  - /
  - '-'
  - '4'
  - '5'
  - '6'
  - E
  - {type: none}
  - F1
  - F2
  - F3
  - {type: none}
  - {type: none}
  - '1'
  - '2'
  - '3'
  - {type: none}
  - {type: none}
  - {type: held}
  - {t: ▽, type: trans}
  - '0'
  - .
  - {type: none}
  ADJ:
  - {type: none}
  - {type: none}
  - $$mdi:apple$$
  - $$mdi:apple$$
  - $$mdi:progress-download$$
  - $$mdi:progress-download$$
  - $$mdi:play-pause$$
  - $$mdi:skip-next$$
  - $$mdi:skip-previous$$
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - $$mdi:backup-restore$$
  - $$mdi:backup-restore$$
  - $$mdi:volume-low$$
  - $$mdi:volume-high$$
  - $$mdi:volume-off$$
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - $$mdi:brightness-7$$
  - $$mdi:brightness-5$$
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: held}
  - {type: held}
  - {type: none}
  - {type: none}
  LOCK:
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
  - {type: none}
combos:
- p: [11, 12]
  k: $$escape$$
  l: [APTMAK]
- p: [12, 13]
  k: $$mdi:keyboard-tab$$
  l: [APTMAK]
- p: [21, 22]
  k: $$mdi:content-copy$$
  l: [APTMAK]
- p: [22, 23]
  k: $$mdi:content-paste$$
  l: [APTMAK]
- p: [21, 22, 23]
  k: $$mdi:content-cut$$
  l: [APTMAK]
  a: bottom
- p: [10, 11]
  k: $$mdi:undo$$
  l: [APTMAK]
- p: [13, 14]
  k: $$mdi:redo$$
  l: [APTMAK]
- p: [16, 17]
  k: (
  l: [APTMAK, SYM, NUM]
- p: [17, 18]
  k: )
  l: [APTMAK, SYM, NUM]
- p: [26, 27]
  k: {h: '[', s: '{'}
  l: [APTMAK, SYM, NUM]
- p: [27, 28]
  k: {h: ']', s: '}'}
  l: [APTMAK, SYM, NUM]
- p: [6, 7]
  k: $$mdi:backspace-outline$$
  l: [APTMAK, NAV, NUM]
- p: [7, 8]
  k: $$mdi:backspace-reverse-outline$$
  l: [APTMAK, NAV, NUM]
- p: [6, 7, 8]
  k: {h: WORD, s: '$$mdi:backspace-outline$$'}
  l: [APTMAK, NUM]
  a: top
- p: [6, 7, 8]
  k: {h: LINE, s: '$$mdi:backspace-outline$$'}
  l: [NAV]
  a: top
- p: [0, 9, 32, 33]
  k: $$mdi:lock-open-outline$$
  l: [APTMAK]
  a: bottom
  o: 0.3
  arc_scale: 1.05
